name: Keep Render Alive

on:
  schedule:
    - cron: "*/14 * * * *"  # Every 14 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep app awake
        run: curl -s https://friend-finder-y6vb.onrender.com > /dev/null
